<?php

/**
 * @copyright 	Andrew Stevens
 * @author 		Andrew Stevens
 * @license 	AGPL-3.0-only
 * @package 	Zyppy Search
 * @link 		https://github.com/asconsulting/contao-zyppy-search
 */



namespace Zyppy\Search\Search;


/**
 * One search result, as plain data.
 *
 * ESCAPING CONTRACT - REVISED IN STEP 10, read this rather than the Step 7
 * version it replaces.
 *
 * Step 7 said "every field is written with textContent; nothing is ever parsed
 * as HTML", because the client assembled each result in JavaScript. Step 10
 * moved rendering back into a Twig template - ONE template, used for both the
 * server-rendered first page and every live update - so that is no longer how
 * this data reaches the page, and the guarantee had to move with it:
 *
 *   - Every field here is UNESCAPED plain text and is escaped ONCE, by Twig,
 *     in search_zyppy.html.twig. The exception is $strContext, which arrives
 *     already escaped and carrying generated <mark> markup (see ContextBuilder)
 *     and is therefore the template's single |raw value.
 *   - $strUrl has ALREADY been through SafeUrl::sanitise(). Twig escaping does
 *     not stop a `javascript:` href - htmlspecialchars() touches no character
 *     in it - so the scheme check is a separate control and it happens here,
 *     covering both render paths at once.
 *   - $arrImage is built by contao.image.studio, so its src/srcset are
 *     generated by Contao rather than taken from user data.
 *
 * The reason this is not a step backwards from Step 7: the alternative was two
 * renderers, which would have made tl_module.searchTpl apply to the first paint
 * and silently not to any update after it. A template whose escaping contract is
 * sentinel-tested and mutation-checked is a better guarantee than a second
 * renderer that no test in this repo can even execute.
 */
final class SearchResultItem
{

	/**
	 * @param array{src: string, srcset: string, sizes: string, width: int|null, height: int|null, alt: string}|null $arrImage
	 */
	public function __construct(
		public readonly string $strTitle,
		public readonly string $strUrl,
		public readonly string $strTitleAttribute,
		public readonly string $strRelevance,
		public readonly string $strContext,
		public readonly string $strTeaser,
		public readonly string $strDescription,
		public readonly array|null $arrImage,
		public readonly bool $blnIsNews,
	)
	{
	}

	/**
	 * The context handed to the per-result template (search_zyppy by default,
	 * or whatever tl_module.searchTpl selects).
	 *
	 * `pageImage` is kept as a plain URL string ALONGSIDE the richer `image`
	 * array, so a site-specific search_* template written against the old shape
	 * goes on rendering rather than silently losing its image.
	 *
	 * @return array<string, mixed>
	 */
	public function toTemplateData(int $intIndex, int $intTotal): array
	{
		return array(
			'class' => trim((0 === $intIndex ? 'first ' : '') . ($intIndex === $intTotal - 1 ? 'last ' : '') . (0 === $intIndex % 2 ? 'even' : 'odd') . ($this->blnIsNews ? ' news' : '')),
			'href' => $this->strUrl,
			'link' => $this->strTitle,
			'title' => $this->strTitleAttribute,
			'relevance' => $this->strRelevance,
			'context' => $this->strContext,
			'hasContext' => '' !== $this->strContext,
			'pageTeaser' => $this->strTeaser,
			'pageDescription' => $this->strDescription,
			'pageImage' => $this->arrImage['src'] ?? '',
			'image' => $this->arrImage,
			'isNews' => $this->blnIsNews,
		);
	}

}
